name: setup-node
description: "Setup Node.js for the build"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Cache Dependencies
      uses: actions/cache@v3
      id: cache-dependencies
      with:
        path: |
          ~/.npm
          ~/.cache/firebase
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      shell: bash
      working-directory: ./functions
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci
    - name: Re-generate prisma
      shell: bash
      working-directory: ./functions
      run: npx prisma generate
