name: Deploy Cloud Functions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Login Firebase
        run: firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
